displayName=Bank and POH searcher
author=Wozak
description=Search your bank and PoH storage locations to see where you have your stuff
tags=bank,storage,poh,house,storage,search,stuff
plugins=com.wheresmystuff.WheresMyStuffPlugin
