displayName=Where's my Stuff
author=Wozak
description=Search your bank and PoH storage locations to see where you have your stuff
tags=bank,storage,poh,house,storage,search,panel
plugins=com.wheresmystuff.WheresMyStuffPlugin